
-- Script de Criação e População das Tabelas de Fichas Místicas Separadas

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

-- ==========================================
-- 1. Criação das Tabelas
-- ==========================================

CREATE TABLE IF NOT EXISTS `VampireClaDefinition` (
  `id` varchar(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `nickname` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `sectAlignment` varchar(255) NOT NULL,
  `mainDisciplines` json NOT NULL,
  `weaknessName` varchar(255) NOT NULL,
  `weaknessDescription` text NOT NULL,
  `weaknessExamples` json DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT current_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `WerewolfTribeDefinition` (
  `id` varchar(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `englishName` varchar(255) NOT NULL,
  `classicName` varchar(255) DEFAULT NULL,
  `description` text NOT NULL,
  `nationAlignment` varchar(255) NOT NULL,
  `mainGifts` json NOT NULL,
  `psychologicalFlawName` varchar(255) NOT NULL,
  `psychologicalFlawDescription` text NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT current_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `MageTraditionDefinition` (
  `id` varchar(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `englishName` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `affinitySphere` varchar(255) NOT NULL,
  `focusInstruments` json NOT NULL,
  `paradigmFlawName` varchar(255) NOT NULL,
  `paradigmFlawDescription` text NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT current_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `HunterCreedDefinition` (
  `id` varchar(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `englishName` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `mainEdges` json NOT NULL,
  `afflictionTriggerName` varchar(255) NOT NULL,
  `afflictionTriggerDescription` text NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT current_timestamp(3) ON UPDATE current_timestamp(3),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==========================================
-- 2. Alteração na Tabela Character
-- ==========================================

ALTER TABLE `Character`
ADD COLUMN `vampireClaId` varchar(36) NULL AFTER `avatarUrl`,
ADD COLUMN `werewolfTribeId` varchar(36) NULL AFTER `vampireClaId`,
ADD COLUMN `mageTraditionId` varchar(36) NULL AFTER `werewolfTribeId`,
ADD COLUMN `hunterCreedId` varchar(36) NULL AFTER `mageTraditionId`;

ALTER TABLE `Character`
ADD CONSTRAINT `fk_character_vampire_cla` FOREIGN KEY (`vampireClaId`) REFERENCES `VampireClaDefinition` (`id`) ON DELETE SET NULL,
ADD CONSTRAINT `fk_character_werewolf_tribe` FOREIGN KEY (`werewolfTribeId`) REFERENCES `WerewolfTribeDefinition` (`id`) ON DELETE SET NULL,
ADD CONSTRAINT `fk_character_mage_tradition` FOREIGN KEY (`mageTraditionId`) REFERENCES `MageTraditionDefinition` (`id`) ON DELETE SET NULL,
ADD CONSTRAINT `fk_character_hunter_creed` FOREIGN KEY (`hunterCreedId`) REFERENCES `HunterCreedDefinition` (`id`) ON DELETE SET NULL;

-- ==========================================
-- 3. Inserção de Dados (Seeding)
-- ==========================================

-- Clãs de Vampiro
INSERT INTO `VampireClaDefinition` (`id`, `name`, `nickname`, `description`, `sectAlignment`, `mainDisciplines`, `weaknessName`, `weaknessDescription`, `weaknessExamples`) VALUES (UUID(), 'Banu Haqim', 'Juízes / Feiticeiros de Assam', 'Guerreiros, juízes e estudiosos que operavam nas sombras do Oriente Médio. São movidos por um senso estrito de justiça e uma fome focada no sangue de outros vampiros.', 'Camarilla', '["Ofuscação","Rapidez","Feitiçaria de Sangue"]', 'Fome de Julgamento / Vício em Vitáe', 'Quando um Banu Haqim bebe o sangue de outro vampiro, ele deve fazer um teste para não entrar em um frenesi de fome, impulsionado pelo desejo de drenar o alvo completamente.', NULL);
INSERT INTO `VampireClaDefinition` (`id`, `name`, `nickname`, `description`, `sectAlignment`, `mainDisciplines`, `weaknessName`, `weaknessDescription`, `weaknessExamples`) VALUES (UUID(), 'Brujah', 'A Ralé', 'A Ralé, rebeldes e insurgentes, lutando com paixão por suas causas desesperadas. Os Brujah sonham com uma sociedade perfeita para os vampiros[cite: 15].', 'Anarquistas', '["Presença","Rapidez","Potência"]', 'Paixão Ardente', 'A dificuldade dos testes para se evitar o frenesi é dois níveis mais alta para os membros do clã Brujah[cite: 15].', NULL);
INSERT INTO `VampireClaDefinition` (`id`, `name`, `nickname`, `description`, `sectAlignment`, `mainDisciplines`, `weaknessName`, `weaknessDescription`, `weaknessExamples`) VALUES (UUID(), 'Gangrel', 'Forasteiro', 'Os nômades Forasteiros são ferozes e selvagens. Estes errantes solitários são a fonte de muitas das histórias que comparam os vampiros a bestas sombrias[cite: 15].', 'Anarquistas', '["Fortitude","Metamorfose","Animalismo"]', 'Marcas da Besta', 'Toda vez que um Gangrel entra em estado de frenesi ele ganha uma característica animalesca permanente. Para cada cinco características adquiridas, o Gangrel perde um ponto em um Atributo Social[cite: 15].', NULL);
INSERT INTO `VampireClaDefinition` (`id`, `name`, `nickname`, `description`, `sectAlignment`, `mainDisciplines`, `weaknessName`, `weaknessDescription`, `weaknessExamples`) VALUES (UUID(), 'Malkavianos', 'Lunáticos', 'Abençoados e amaldiçoados com uma percepção fragmentada da realidade. A loucura do clã esconde verdades ocultas que os outros membros são incapazes de enxergar.', 'Camarilla', '["Auspícios","Ofuscação","Demência"]', 'Perturbação Mental', 'Todo Malkaviano possui uma psicose ou distúrbio mental permanente que se manifesta de forma mais agressiva quando o personagem sofre falhas críticas ou surtos de estresse.', '["Paranoia Obsessiva","Visões e Alucinações Auditivas"]');
INSERT INTO `VampireClaDefinition` (`id`, `name`, `nickname`, `description`, `sectAlignment`, `mainDisciplines`, `weaknessName`, `weaknessDescription`, `weaknessExamples`) VALUES (UUID(), 'Ministério', 'As Serpentes / Ministry', 'Antigos Seguidores de Set. São mestres da mentira, subversão, corrupção espiritual e quebra de dogmas sociais[cite: 17]. Operam como os donos dos segredos e prazeres ilícitos da noite.', 'Anarquistas', '["Ofuscação","Presença","Metamorfose"]', 'Aversão à Luz / Corrupção da Carne', 'As Serpentes sofrem penalidades severas em seus dados de ação e testes físicos se expostas a luzes artificiais intensas, holofotes ou chamas diretas.', NULL);
INSERT INTO `VampireClaDefinition` (`id`, `name`, `nickname`, `description`, `sectAlignment`, `mainDisciplines`, `weaknessName`, `weaknessDescription`, `weaknessExamples`) VALUES (UUID(), 'Nosferatu', 'Rato de Esgoto', 'Deformados e reclusos, os horrorosos Ratos de Esgoto estão para sempre banidos da sociedade humana, mas guardam segredos sobre a escuridão que os esconde[cite: 15].', 'Camarilla', '["Ofuscação","Animalismo","Potência"]', 'Deformidade Repugnante', 'Aparência permanentemente 0. A maioria das ações Sociais baseadas na primeira impressão falham automaticamente[cite: 15].', '["Carne e pele secas e quebradiças, deixando pequenos pedaços que parecem madeira seca pelo chão[cite: 15]","Nenhum pêlo no corpo e pele com a viscosidade de uma lesma, deixando muco onde encostar[cite: 15]"]');
INSERT INTO `VampireClaDefinition` (`id`, `name`, `nickname`, `description`, `sectAlignment`, `mainDisciplines`, `weaknessName`, `weaknessDescription`, `weaknessExamples`) VALUES (UUID(), 'Ravnos', 'Malandros / Errantes', 'Nômades mestres da ilusão, truques mentais e fuga de amarras sociais. São caçados pela sua reputação de ladrões e trapaceiros incuráveis do submundo.', 'Autônomos / Independentes', '["Animalismo","Ofuscação","Quimerismo / Presença"]', 'A Besta Inquieta / Vício do Estigma', 'Um Ravnos não consegue permanecer no mesmo local por muito tempo. Se ele dormir no mesmo refúgio por mais de uma noite consecutiva, a Besta racha sua mente, drenando sua Força de Vontade.', NULL);
INSERT INTO `VampireClaDefinition` (`id`, `name`, `nickname`, `description`, `sectAlignment`, `mainDisciplines`, `weaknessName`, `weaknessDescription`, `weaknessExamples`) VALUES (UUID(), 'Salubri', 'Ciclistas / Os De Três Olhos', 'Uma linhagem caçada e quase extinta de curandeiros e guerreiros místicos. São marcados por possuírem um terceiro olho físico na testa e por carregar o peso do fardo espiritual da humanidade.', 'Autônomos / Independentes', '["Auspícios","Fortitude","Obeah / Valeren"]', 'Alimentação Dolorosa / O Terceiro Olho', 'O terceiro olho do Salubri chora lágrimas de sangue quando ele usa seus poderes. Além disso, ele não consegue se alimentar de uma presa que não dê o sangue voluntariamente sem sofrer remorso mecânico.', NULL);
INSERT INTO `VampireClaDefinition` (`id`, `name`, `nickname`, `description`, `sectAlignment`, `mainDisciplines`, `weaknessName`, `weaknessDescription`, `weaknessExamples`) VALUES (UUID(), 'Toreador', 'Degenerado', 'Amantes da arte e da estética, os Degenerados estão presos na estagnação da não-vida. Os Toreador são apaixonados e decadentes[cite: 15].', 'Camarilla', '["Presença","Rapidez","Auspícios"]', 'Transe da Beleza / Fascinação', 'Quando um Toreador vê algo realmente maravilhoso, precisa ser bem sucedido num teste de Autocontrole (dif. 6) ou se encantará. O Toreador será tomado por um êxtase de fascinação durante uma cena e não pode se defender se atacado[cite: 15].', NULL);
INSERT INTO `VampireClaDefinition` (`id`, `name`, `nickname`, `description`, `sectAlignment`, `mainDisciplines`, `weaknessName`, `weaknessDescription`, `weaknessExamples`) VALUES (UUID(), 'Tremere', 'Feiticeiro', 'Um clã de magos do sangue, os Feiticeiros não são nada confiáveis... e sim temíveis[cite: 15].', 'Camarilla', '["Feitiçaria de Sangue","Auspícios","Dominação"]', 'Laço de Sangue do Conselho', 'Todo neófito Tremere tomou do sangue dos sete anciões do clã. A dificuldade de qualquer tentativa de Dominação feita por um superior do clã é reduzida em 1. Um Tremere é fiel ao clã acima de tudo[cite: 15].', NULL);
INSERT INTO `VampireClaDefinition` (`id`, `name`, `nickname`, `description`, `sectAlignment`, `mainDisciplines`, `weaknessName`, `weaknessDescription`, `weaknessExamples`) VALUES (UUID(), 'Tzimisce', 'Demônios / Construtores de Carne', 'Tiranos territoriais que dominavam os castelos do Leste Europeu. Possuem controle absoluto sobre a biologia e a ossatura, moldando a própria carne e a de suas vítimas como se fossem argila viva.', 'Autônomos / Independentes', '["Animalismo","Auspicíos","Vicissitude / Metamorfose"]', 'Vínculo Territorial / Sono da Terra Natal', 'Um Tzimisce precisa dormir cercado por pelo menos um punhado de terra de um local de extrema importância histórica para ele (como sua terra natal ou seu local de refúgio inicial). Caso contrário, ele perde dados de ação a cada noite.', NULL);
INSERT INTO `VampireClaDefinition` (`id`, `name`, `nickname`, `description`, `sectAlignment`, `mainDisciplines`, `weaknessName`, `weaknessDescription`, `weaknessExamples`) VALUES (UUID(), 'Ventrue', 'Sangue Azul', 'Relutantes membros aristocratas, os de Sangue Azul se reconciliam com sua maldição impondo as Tradições e a Máscara[cite: 15].', 'Camarilla', '["Dominação","Fortitude","Presença"]', 'Paladar Exigente', 'Cada Ventrue só pode se alimentar de um tipo de sangue mortal[cite: 15].', '["Sangue de garotas jovens embriagadas com vinho[cite: 15]","Sangue de adolescentes sob a influência de drogas[cite: 15]"]');
INSERT INTO `VampireClaDefinition` (`id`, `name`, `nickname`, `description`, `sectAlignment`, `mainDisciplines`, `weaknessName`, `weaknessDescription`, `weaknessExamples`) VALUES (UUID(), 'Sangues-Ralos', 'Thin-Bloods / Décima Quinta Geração', 'Vampiros de gerações muito distantes de Caim. O sangue deles é ralo e fraco[cite: 17]; eles são desprezados pelos anciões, mas possuem a capacidade única de andar sob o sol por alguns minutos e criar alquimia de sangue.', 'Autônomos / Banidos', '["Alquimia de Sangue-Ralo"]', 'Fragilidade Clínica / Rejeição do Sangue', 'Não possuem clã ou disciplinas nativas estáveis[cite: 17]. Não conseguem criar carniçais ou laços de sangue normais e são caçados como anomalias pela Camarilla.', NULL);
INSERT INTO `VampireClaDefinition` (`id`, `name`, `nickname`, `description`, `sectAlignment`, `mainDisciplines`, `weaknessName`, `weaknessDescription`, `weaknessExamples`) VALUES (UUID(), 'Caitiff', 'Os Sem-Clã', 'Vampiros abandonados ou cujos traços de sangue não manifestaram nenhuma característica de clã[cite: 17]. São vistos como bastardos e cidadãos de segunda classe na sociedade dos Membros.', 'Anarquistas / Autônomos', '["Qualquer (Custo de XP universalizado)"]', 'Estigma Social / Ausência de Linhagem', 'Não possuem fraqueza biológica herdada, mas sofrem falha automática ou penalidades severas em testes de reputação, status e diplomacia com a Camarilla[cite: 17].', NULL);

-- Tribos de Lobisomem
INSERT INTO `WerewolfTribeDefinition` (`id`, `name`, `englishName`, `classicName`, `description`, `nationAlignment`, `mainGifts`, `psychologicalFlawName`, `psychologicalFlawDescription`) VALUES (UUID(), 'Senhores das Sombras', 'Shadow Lords', NULL, 'Mestres da política e da intimidação, operam através de manipulação e controle para liderar e expor a corrupção.', 'Membros da Nação Garou', '["Dons do Augúrio: Philodox","Dons Universais da Cidade"]', 'Orgulho Tirânico', 'Sua obsessão por controle e hierarquia faz com que sofram penalidades em dados de Empatia caso precisem aceitar ordens de outrem ou demonstrar fraqueza social[cite: 4].');
INSERT INTO `WerewolfTribeDefinition` (`id`, `name`, `englishName`, `classicName`, `description`, `nationAlignment`, `mainGifts`, `psychologicalFlawName`, `psychologicalFlawDescription`) VALUES (UUID(), 'Crias de Fenris', 'Get of Fenris', NULL, 'Guerreiros implacáveis cujo extremismo os levou a serem marginalizados ou expulsos da Nação Garou tradicional.', 'Culto Extremista (Marginalizados / Expulsos)', '["Dons do Augúrio: Ahroun"]', 'Hauglosk Fanático / Fúria Cega', 'Devido ao seu extremismo de combate, a dificuldade para evitar o estado de Hauglosk (fanatismo cego) é agravada, atacando aliados que mostrem qualquer sinal de hesitação[cite: 1, 4].');
INSERT INTO `WerewolfTribeDefinition` (`id`, `name`, `englishName`, `classicName`, `description`, `nationAlignment`, `mainGifts`, `psychologicalFlawName`, `psychologicalFlawDescription`) VALUES (UUID(), 'Fúrias Negras', 'Black Furies', NULL, 'Guerreiras ferozes dedicadas a proteger os inocentes e os lugares sagrados da natureza. Em São Paulo, atuam fortemente na proteção de minorias e mananciais[cite: 17].', 'Membros da Nação Garou', '["Dons do Augúrio: Ahroun","Vida"]', 'Vingança Justa / Fúria contra o Opressor', 'Sofrem dificuldades aumentadas em rolagens de Autocontrole se testemunharem atos de opressão contra inocentes ou profanação de solo sagrado[cite: 4].');
INSERT INTO `WerewolfTribeDefinition` (`id`, `name`, `englishName`, `classicName`, `description`, `nationAlignment`, `mainGifts`, `psychologicalFlawName`, `psychologicalFlawDescription`) VALUES (UUID(), 'Portadores da Luz', 'Brought Light', 'Crianças de Gaia', 'Pacificadores e diplomatas que buscam a cura e a reconciliação no fragmentado submundo sobrenatural.', 'Membros da Nação Garou', '["Dons do Augúrio: Galliard","Vida"]', 'Aversão ao Conflito / Hesitação Pacifista', 'Caso tentem iniciar um ataque físico surpresa ou uma ação letal direta desprovida de negociação prévia, perdem dados da pilha de ação[cite: 4].');
INSERT INTO `WerewolfTribeDefinition` (`id`, `name`, `englishName`, `classicName`, `description`, `nationAlignment`, `mainGifts`, `psychologicalFlawName`, `psychologicalFlawDescription`) VALUES (UUID(), 'Peregrinos Silenciosos', 'Silent Striders', NULL, 'Viajantes místicos que atuam como mensageiros e lidam com os mortos. Estão sempre em movimento pelas rodovias e estradas.', 'Membros da Nação Garou', '["Rapidez","Correspondência / Espírito"]', 'Assombrado pelos Mortos', 'Devido à sua proximidade com o além, fantasmas e aparições perturbam constantemente seu descanso no refúgio, gerando riscos de testes de Força de Vontade ao amanhecer[cite: 4].');
INSERT INTO `WerewolfTribeDefinition` (`id`, `name`, `englishName`, `classicName`, `description`, `nationAlignment`, `mainGifts`, `psychologicalFlawName`, `psychologicalFlawDescription`) VALUES (UUID(), 'Andarilhos do Asfalto', 'Glass Walkers', NULL, 'Especialistas em tecnologia e urbanismo, adaptados à vida moderna. Controlam grandes territórios industriais e digitais em São Paulo[cite: 17].', 'Membros da Nação Garou', '["Dons Universais da Cidade","Tempo / Matéria"]', 'Desconexão com o Selvagem / Película Espessa', 'Sua mente é altamente tecnológica e cética, o que aumenta em +2 a dificuldade de qualquer teste místico de travessia espiritual para a Umbra Selvagem[cite: 4].');
INSERT INTO `WerewolfTribeDefinition` (`id`, `name`, `englishName`, `classicName`, `description`, `nationAlignment`, `mainGifts`, `psychologicalFlawName`, `psychologicalFlawDescription`) VALUES (UUID(), 'Senhores da Presa', 'Silver Fangs', NULL, 'A nobreza tradicional dos lobisomens, agora lutando para manter sua relevância em um mundo fragmentado.', 'Líderes Tradicionais (Nação Garou)', '["Dons do Augúrio: Philodox","Presença"]', 'Instabilidade da Linhagem / Decadência Nobre', 'O peso da herança e da consanguinidade gera surtos de exaustão mental, forçando falhas automáticas em testes sob estresse caso sua autoridade seja questionada[cite: 4].');
INSERT INTO `WerewolfTribeDefinition` (`id`, `name`, `englishName`, `classicName`, `description`, `nationAlignment`, `mainGifts`, `psychologicalFlawName`, `psychologicalFlawDescription`) VALUES (UUID(), 'Roedores de Ossos', 'Bone Gnawers', NULL, 'Sobreviventes urbanos que conhecem os segredos das ruas e os marginalizados. Habitam favelas e cortiços da cidade[cite: 17].', 'Membros da Nação Garou', '["Dons Universais da Cidade","Animalismo"]', 'Estigma de Sarjeta / Repulsão Social', 'Vistos com nojo pela alta sociedade Garou e humana; falham automaticamente em primeiras impressões de Etiqueta ou diplomacia corporativa[cite: 4].');
INSERT INTO `WerewolfTribeDefinition` (`id`, `name`, `englishName`, `classicName`, `description`, `nationAlignment`, `mainGifts`, `psychologicalFlawName`, `psychologicalFlawDescription`) VALUES (UUID(), 'Filhos do Vento', 'Children of the Sun', 'Uktena', 'Guardiões de segredos místicos e espirituais profundos. Infiltrados em círculos de ocultismo urbano.', 'Membros da Nação Garou', '["Dons do Augúrio: Theurge","Entropia"]', 'Obsessão pelo Proibido / Segredo Sombrio', 'Sua curiosidade insaciável por conhecimento corrompido aumenta as chances de contaminação espiritual por parasitas cósmicos[cite: 4].');
INSERT INTO `WerewolfTribeDefinition` (`id`, `name`, `englishName`, `classicName`, `description`, `nationAlignment`, `mainGifts`, `psychologicalFlawName`, `psychologicalFlawDescription`) VALUES (UUID(), 'Guardiões da Floresta', 'Wardens of the Forest', 'Wendigo', 'Defensores ferozes das terras selvagens e tradições ancestrais. Radicados nos extremos de preservação ambiental da Cantareira[cite: 17].', 'Membros da Nação Garou', '["Dons do Augúrio: Ahroun","Forças"]', 'Preconceito Ancestral / Isolacionismo', 'Recusam-se a colaborar ou receber auxílio de personagens de linhagem puramente urbana (como os Andarilhos do Asfalto), sofrendo severas penalidades sociais[cite: 4].');
INSERT INTO `WerewolfTribeDefinition` (`id`, `name`, `englishName`, `classicName`, `description`, `nationAlignment`, `mainGifts`, `psychologicalFlawName`, `psychologicalFlawDescription`) VALUES (UUID(), 'Irmãos do Inverno', 'Winterwolves', 'Rostos Prateados', 'Adicionados como parte das reformulações de clãs. Sobreviventes implacáveis das franjas geladas ou isoladas da sociedade Garou.', 'Independentes / Isolados', '["Fortitude","Dons do Augúrio: Ragabash"]', 'Harano Inerente / Melancolia Espiritual', 'São propensos a cair no estado de Harano (depressão espiritual do apocalipse) com muito mais facilidade ao término de aventuras fracassadas[cite: 1, 4].');
INSERT INTO `WerewolfTribeDefinition` (`id`, `name`, `englishName`, `classicName`, `description`, `nationAlignment`, `mainGifts`, `psychologicalFlawName`, `psychologicalFlawDescription`) VALUES (UUID(), 'Vozes da Terra', 'Earth-Voices', 'Fidalgos de Vidro / Stargazers', 'Filósofos e meditadores que buscam o equilíbrio e a iluminação. Operam como os conselheiros neutros das matilhas.', 'Independentes / Conselheiros Autônomos', '["Mente","Dons do Augúrio: Philodox"]', 'Desapego Prático / Alheamento da Realidade', 'Sua busca por iluminação os torna distantes de urgências físicas mundanas; sofrem penalidades em rolagens de Prontidão ou Iniciativa de combate surpresa[cite: 4].');

-- Tradições de Mago
INSERT INTO `MageTraditionDefinition` (`id`, `name`, `englishName`, `description`, `affinitySphere`, `focusInstruments`, `paradigmFlawName`, `paradigmFlawDescription`) VALUES (UUID(), 'Adeptos da Virtualidade', 'Virtual Adepts', 'Tecnómagos e hackers que entendem a realidade como um código de computador passível de ser ''hackeado''[cite: 1]. Dominam a infraestrutura digital e redes ocultas[cite: 17].', 'Correspondência', '["Notebook Tecnomante Customizado","Drones de Vigilância Térmica","Algoritmos e Hardware de Santa Ifigênia"]', 'Dependência de Hardware / Foco Rígido', 'Sua magia é intrinsecamente ligada à tecnologia. Se o Mago for privado de computadores ou rede de dados, sua dificuldade de conjuração é severamente penalizada.');
INSERT INTO `MageTraditionDefinition` (`id`, `name`, `englishName`, `description`, `affinitySphere`, `focusInstruments`, `paradigmFlawName`, `paradigmFlawDescription`) VALUES (UUID(), 'Coro Celestial', 'Celestial Chorus', 'Buscam o divino por meio da crença e da devoção em uma força unificada[cite: 1]. Operam em santuários e basílicas tradicionais da cidade[cite: 17].', 'Primórdio', '["Orações, Cânticos e Hinos","Símbolos Religiosos Sagrados","Incensos e Velas Rituais"]', 'Dogmatismo Rígido', 'Seus feitiços exigem pureza de intenção e fé. Caso execute ações que entrem em contradição direta com seus votos morais, o Paradoxo ricocheteia com o dobro de agressividade[cite: 1, 4].');
INSERT INTO `MageTraditionDefinition` (`id`, `name`, `englishName`, `description`, `affinitySphere`, `focusInstruments`, `paradigmFlawName`, `paradigmFlawDescription`) VALUES (UUID(), 'Culto do Êxtase', 'Cult of Ecstasy', 'Buscam a iluminação através dos sentidos, emoções, meditação e alteração da percepção e do tempo[cite: 1].', 'Tempo', '["Músicas Dinâmicas / Dança","Estimulantes e Substâncias Alteradoras","Meditação Sensorial Intensa"]', 'Alheamento Temporal / Distração', 'Sua manipulação constante da linha do tempo gera desorientação. Sofrem penalidades em rolagens de Prontidão e Iniciativa ao saírem de feitiços de transe temporal[cite: 4].');
INSERT INTO `MageTraditionDefinition` (`id`, `name`, `englishName`, `description`, `affinitySphere`, `focusInstruments`, `paradigmFlawName`, `paradigmFlawDescription`) VALUES (UUID(), 'Eutanatos', 'Euthanatoi', 'Sacerdotes da morte, do destino e do renascimento. Controlam o ciclo de almas através da entropia[cite: 1] e vigiam os cemitérios urbanos[cite: 17].', 'Entropia', '["Dados, Moedas e Jogos de Azar","Adagas Rituais","Cinzas e Símbolos de Decomposição"]', 'O Peso do Destino / Máscara Fúnebre', 'Lidar com o decaimento torna sua aura pesada. Humanas comuns sentem repulsa inconsciente, aplicando penalidades em testes sociais de primeira impressão (Lábia/Etiqueta)[cite: 4].');
INSERT INTO `MageTraditionDefinition` (`id`, `name`, `englishName`, `description`, `affinitySphere`, `focusInstruments`, `paradigmFlawName`, `paradigmFlawDescription`) VALUES (UUID(), 'Filhos do Éter', 'Sons of Ether', 'Cientistas idealistas, rebeldes e inventores que utilizam a eter-ciência em vez da ortodoxia Tecnocrática[cite: 1]. Operam em laboratórios e galpões secretos[cite: 17].', 'Matéria', '["Gambiarras de Engenharia / Óculos Táticos","Raios de Plasma e Bobinas Personalizadas","Manuais Científicos Alternativos"]', 'Instabilidade da Invenção', 'Seus aparatos científicos desafiam o Consenso Público de forma vulgar. Falhas em seus testes de Matéria frequentemente explodem as engenhocas, causando dano físico direto ao Mago[cite: 1, 4].');
INSERT INTO `MageTraditionDefinition` (`id`, `name`, `englishName`, `description`, `affinitySphere`, `focusInstruments`, `paradigmFlawName`, `paradigmFlawDescription`) VALUES (UUID(), 'Irmandade de Akasha', 'Akashic Brotherhood', 'Monges guerreiros focados no domínio da mente e do corpo por meio de energia interior[cite: 1]. Concentrados na região tradicional da Liberdade[cite: 17].', 'Mente', '["Exercícios de Respiração (Pranayama)","Movimentos de Artes Marciais / Katana","Meditação Ascética Concentrada"]', 'Rigidez Marcial / Necessidade de Foco', 'Sua magia exige equilíbrio biológico e mental. Estar sob efeito de venenos, ferimentos graves ou ambientes de barulho caótico (Marginais) obstaculiza o uso de seus poderes interiores[cite: 4].');
INSERT INTO `MageTraditionDefinition` (`id`, `name`, `englishName`, `description`, `affinitySphere`, `focusInstruments`, `paradigmFlawName`, `paradigmFlawDescription`) VALUES (UUID(), 'Oradores dos Sonhos', 'Dreamspeakers', 'Xamãs que servem como pontes entre o mundo material, espiritual e os ancestrais[cite: 1]. Infiltrados nas reservas e matas periféricas.', 'Espírito', '["Tambores e Chocalhos Rituais","Ervas Queimadas e Defumações","Pactos de Sangue com Espíritos Locais"]', 'Magnetismo Espiritual', 'Sua proximidade com o Véu faz com que entidades da Umbra fiquem constantemente atraídas pelo seu rastro, aumentando as chances de encontros perigosos com o invisível durante as patrulhas[cite: 4].');
INSERT INTO `MageTraditionDefinition` (`id`, `name`, `englishName`, `description`, `affinitySphere`, `focusInstruments`, `paradigmFlawName`, `paradigmFlawDescription`) VALUES (UUID(), 'Ordem de Hermes', 'Order of Hermes', 'Mestres clássicos de rituais, invocação e numerologia esotérica. Baseiam-se em textos e pactos antigos[cite: 1]. Operam na Capela Central de Perdizes[cite: 17].', 'Forças', '["Grimórios Antigos e Pergaminhos","Palavras de Comando em Enochiano","Cálculos Matemáticos Planificados"]', 'Complexidade Ritual / Verbose', 'Seus feitiços exigem gestos precisos e entonação perfeita de palavras arcanas. São incapazes de lançar feitiços de forma silenciosa ou totalmente paralisados, sob risco de sofrerem Choque de Retorno imediato[cite: 1, 4].');
INSERT INTO `MageTraditionDefinition` (`id`, `name`, `englishName`, `description`, `affinitySphere`, `focusInstruments`, `paradigmFlawName`, `paradigmFlawDescription`) VALUES (UUID(), 'Verbena', 'Verbena', 'Bruxos pagãos primitivos e druidas que manipulam os fluxos de vida e sangue da natureza[cite: 1]. Escondem-se nas matas fechadas do Mandaqui e Cantareira[cite: 17].', 'Vida', '["Sacrifício de Sangue Próprio ou Animal","Ervas Silvestres, Raízes e Caldeirões","Entalhes em Madeira e Runas da Casca de Árvore"]', 'Paradoxo da Carne / Dano Primitivo', 'Sua magia é visceral, orgânica e sangrenta. O uso de rituais de transmutação biológica em locais públicos gera repulsa imediata no Consenso, gerando anomalias físicas grotescas na região[cite: 1, 4].');

-- Credos de Caçador
INSERT INTO `HunterCreedDefinition` (`id`, `name`, `englishName`, `description`, `mainEdges`, `afflictionTriggerName`, `afflictionTriggerDescription`) VALUES (UUID(), 'Inquisidores', 'Inquisitive', 'Caçadores focados em monitorar, catalogar e desvendar os segredos do sobrenatural. Eles acreditam que o conhecimento e a informação correta são as melhores armas para desmantelar os monstros.', '["Investigação","Drones de Vigilância Térmica e Rastreamento"]', 'Obscurantismo Paralisante', 'Se deparar com um fenômeno sobrenatural inexplicável ou perder registros cruciais de uma investigação faz com que seu Ímpeto desabe, jogando o caçador em Paranoia Obsessiva.');
INSERT INTO `HunterCreedDefinition` (`id`, `name`, `englishName`, `description`, `mainEdges`, `afflictionTriggerName`, `afflictionTriggerDescription`) VALUES (UUID(), 'Vingadores', 'Avenger', 'Movidos pelo ódio e pelo desejo de retribuição. Não buscam entender ou salvar; seu único objetivo é a aniquilação total e violenta de qualquer criatura da noite que cruze seu caminho.', '["Armas de Fogo / Armas Brancas","Munição de Fósforo Branco / Modificações de Dano Agravado"]', 'Fúria Cegante / Obsessão por Sangue', 'Falhar em um ataque ou ver um monstro escapar ileso faz com que o caçador perca a cautela tática, sofrendo severas penalidades em dados de Defesa e Furtividade devido à raiva cega[cite: 4].');
INSERT INTO `HunterCreedDefinition` (`id`, `name`, `englishName`, `description`, `mainEdges`, `afflictionTriggerName`, `afflictionTriggerDescription`) VALUES (UUID(), 'Protetores', 'Martyr', 'Colocam a segurança dos inocentes acima de tudo, inclusive de suas próprias vidas. Operam como escudos humanos, infiltrados em igrejas, ONGs e comunidades carentes para vigiar os civis.', '["Fé Inabalável / Socorro Tático","Colete de Kevlar Pesado / Injetores de Adrenalina Pura"]', 'Trauma de Pilar / Culpa do Sobrevivente', 'Se um civil inocente ou um aliado próximo (Pilar) sofrer ferimentos graves na cena devido à sua falha protetiva, o caçador entra instantaneamente em Aflição profunda, travando o gatilho[cite: 1, 4].');
INSERT INTO `HunterCreedDefinition` (`id`, `name`, `englishName`, `description`, `mainEdges`, `afflictionTriggerName`, `afflictionTriggerDescription`) VALUES (UUID(), 'Juízes', 'Judgmatic', 'Eles enxergam a caçada como um tribunal. Avaliam as ações dos monstros e aplicam sentenças proporcionais: destroem os assassinos brutais, mas podem poupar ou usar criaturas que mantenham sua humanidade.', '["Liderança / Intimidação","Táticas de Cerco e Interrogatório Urbano"]', 'Crise de Convicção / Dúvida Moral', 'Ser forçado a quebrar seu próprio código moral (como executar uma presa comprovadamente inocente) estraçalha sua obstinação, zerando o Ímpeto e gerando o estado de Traumatizado[cite: 1, 4].');
INSERT INTO `HunterCreedDefinition` (`id`, `name`, `englishName`, `description`, `mainEdges`, `afflictionTriggerName`, `afflictionTriggerDescription`) VALUES (UUID(), 'Redentores', 'Redeemer', 'Acreditam que os monstros são vítimas de uma maldição e buscam salvá-los ou curá-los. Tentam apelar para a antiga humanidade das criaturas através da diplomacia, recorrendo à violência apenas como último recurso.', '["Empatia / Persuasão","Gabaritos de Contenção Não-Letal / Sedativos"]', 'Desespero Utópico', 'Testemunhar um monstro abraçar o sadismo por completo ou ver uma tentativa de cura falhar tragicamente faz o caçador cair em melancolia, impedindo o ganho de Ímpeto por 3 noites[cite: 1, 4].');

COMMIT;
